#!/bin/sh
# Prevent committing any files under node_modules
staged=$(git diff --cached --name-only)
echo "$staged" | grep -q '^node_modules/' && {
  echo "\nError: you have staged files in node_modules.\nRemove them (git reset <file>) before committing."
  exit 1
}
exit 0
